Repository Kelvinn03/uts-fakerapi, pull requests merged in 2025-04, with the labels that each got.

#2 pull request for cute endpoints(⁠｡⁠･⁠ω⁠･⁠｡⁠)⁠ﾉ⁠♡
  src/api/components/ascii/ascii-controller.js
  src/api/components/ascii/ascii-repository.js
  src/api/components/ascii/ascii-route.js
  src/api/components/ascii/ascii-service.js
  src/api/components/creditCards/creditcards-controller.js
  src/api/components/creditCards/creditcards-repository.js
  src/api/components/creditCards/creditcards-route.js
  src/api/components/creditCards/creditcards-service.js
  src/api/components/funfact/funfact-controller.js
  src/api/components/funfact/funfact-repository.js
  src/api/components/funfact/funfact-route.js
  src/api/components/funfact/funfact-service.js
  src/api/components/images/images-controller.js
  src/api/components/images/images-repository.js
  src/api/components/images/images-route.js
  src/api/components/images/images-service.js
  src/api/routes.js
  src/models/ascii-schema.js
  src/models/creditcards-schema.js
  src/models/funfact-schema.js
  src/models/images-schema.js
Labels: enhancement

#3 another new cute features for endpoints (˵ •̀ ᴗ - ˵ ) ✧
  src/api/components/funfact/funfact-controller.js
  src/api/components/funfact/funfact-repository.js
  src/api/components/funfact/funfact-route.js
  src/api/components/funfact/funfact-service.js
Labels: enhancement

#4 pwease merge so my branch is up-to-date:3
  .env.example
  .gitattribute
  .gitignore
  src/api/components/address/address-controller.js
  src/api/components/address/address-repository.js
  src/api/components/books/books-controller.js
  src/utils/randomizer.js
Labels: help wanted

#6 Add Products, Places & Texts endpoints (+ models, seeders, docs)
  package-lock.json
  src/api/components/places/place-controller.js
  src/api/components/places/place-repository.js
  src/api/components/places/place-route.js
  src/api/components/places/place-service.js
  src/api/components/products/product-controller.js
  src/api/components/products/product-repository.js
  src/api/components/products/product-route.js
  src/api/components/products/product-service.js
  src/api/components/texts/text-controller.js
  src/api/components/texts/text-repository.js
  src/api/components/texts/text-route.js
  src/api/components/texts/text-service.js
  src/api/routes.js
  src/models/places.js
  src/models/products.js
  src/models/text.js
Labels: enhancement

#10 refactor miawwww:3333
  src/api/components/ascii/ascii-controller.js
  src/api/components/ascii/ascii-repository.js
  src/api/components/ascii/ascii-route.js
  src/api/components/ascii/ascii-seeding.js
  src/api/components/ascii/ascii-service.js
  src/api/components/creditCards/creditcards-controller.js
  src/api/components/creditCards/creditcards-repository.js
  src/api/components/creditCards/creditcards-route.js
  src/api/components/creditCards/creditcards-service.js
  src/api/components/funfact/funfact-controller.js
  src/api/components/funfact/funfact-repository.js
  src/api/components/funfact/funfact-route.js
  src/api/components/funfact/funfact-service.js
  src/api/components/images/images-controller.js
  src/api/components/images/images-repository.js
  src/api/components/images/images-route.js
  src/api/components/images/images-service.js
Labels: enhancement

#13 fix some buggies and refactor names:>
  src/api/components/ascii/ascii-controller.js
  src/api/components/ascii/ascii-route.js
  src/api/components/ascii/ascii-service.js
  src/api/components/creditCard/creditcard-controller.js
  src/api/components/funfact/funfact-controller.js
  src/api/components/funfact/funfact-service.js
  src/api/components/images/image-controller.js
Labels: bug

#15 puuuwlll requwestttt:3333
  src/api/components/ascii/ascii-controller.js
  src/api/components/ascii/ascii-repository.js
  src/api/components/ascii/ascii-route.js
  src/api/components/ascii/ascii-seeder.js
  src/api/components/ascii/ascii-service.js
  src/api/components/creditCard/creditcard-controller.js
  src/api/components/creditCard/creditcard-repository.js
  src/api/components/creditCard/creditcard-route.js
  src/api/components/creditCard/creditcard-seeder.js
  src/api/components/creditCard/creditcards-service.js
  src/api/components/funfact/funfact-controller.js
  src/api/components/funfact/funfact-repository.js
  src/api/components/funfact/funfact-route.js
  src/api/components/funfact/funfact-seeder.js
  src/api/components/funfact/funfact-service.js
  src/api/components/images/image-controller.js
  src/api/components/images/image-route.js
  src/api/components/images/image-seeder.js
  src/api/components/images/image-service.js
  src/models/ascii-schema.js
  src/models/creditcards-schema.js
  src/models/funfact-schema.js
  src/models/images-schema.js
Labels: bug, enhancement

#14 Eric
  package-lock.json
  package.json
  src/api/components/quotes/quotes-controller.js
  src/api/components/quotes/quotes-repository.js
  src/api/components/quotes/quotes-route.js
  src/api/components/quotes/quotes-seeder.js
  src/api/components/quotes/quotes-service.js
  src/api/components/texts/text-controller.js
  src/api/components/texts/text-repository.js
  src/api/components/texts/text-route.js
  src/api/components/texts/text-service.js
  src/api/components/texts/texts-controller.js
  src/api/components/texts/texts-repository.js
  src/api/components/texts/texts-route.js
  src/api/components/texts/texts-seeder.js
  src/api/components/texts/texts-service.js
  src/api/routes.js
  src/models/quotes-schema.js
  src/models/text.js
  src/models/texts-schema.js
Labels: bug, enhancement
